project_id = "auhupuupxwxoxmcjxaxk"

[functions.create-admin-user]
verify_jwt = false

[functions.send-client-welcome]
verify_jwt = false

[functions.send-quotation-email]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.create-manager]
verify_jwt = false

[functions.create-client]
verify_jwt = true

[functions.create-stripe-payment]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-payment-verification-email]
verify_jwt = false

[functions.upload-pdf-r2]
verify_jwt = false

[functions.send-quotation-acceptance-email]
verify_jwt = false

[functions.send-client-quotation-notification]
verify_jwt = false

[functions.test-r2-upload]
verify_jwt = false
